# Generated by Django 4.1.5 on 2023-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_project_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
